// packages/dashboard-angular/src/components/realtime.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input, ViewEncapsulation } from "@angular/core";
import type { RealtimeResponse } from "../types";
import { formatInt } from "../format";
import { WBX_CSS } from "../theme";

@Component({
  selector: "wb-realtime",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  styles: [WBX_CSS],
  template: `
    <div data-wbx data-wbx-part="realtime">
      <div data-wbx-title>LIVE VISITORS</div>
      <div style="display: flex; align-items: baseline; gap: 12px;">
        <span data-wbx-pulse aria-hidden="true"></span>
        <span data-wbx-value>{{ online }}</span>
        <span data-wbx-subtle>online now</span>
      </div>

      <div *ngIf="topPages.length > 0" style="margin-top: 20px;">
        <div data-wbx-title style="margin-bottom: 8px;">ACTIVE PAGES</div>
        <div *ngFor="let p of topPages" data-wbx-row>
          <span
            [title]="p.path"
            style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 70%;"
          >
            {{ p.path || "/" }}
          </span>
          <strong style="font-variant-numeric: tabular-nums;">{{ fmt(p.visitors) }}</strong>
        </div>
      </div>

      <div *ngIf="showRecent && data.recent.length > 0" style="margin-top: 20px;">
        <div data-wbx-title style="margin-bottom: 8px;">RECENT</div>
        <div *ngFor="let r of data.recent | slice:0:8" data-wbx-row>
          <span style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 70%;">
            {{ r.path || "/" }}
          </span>
          <span data-wbx-subtle>{{ r.country_code }} {{ r.device }}</span>
        </div>
      </div>
    </div>
  `,
})
export class RealtimeComponent {
  /** Response from `client.realtime()`. */
  @Input({ required: true }) data!: RealtimeResponse;

  /** Limit the "active pages" list (default 5). */
  @Input() topPagesLimit = 5;

  /** Show the scrolling recent feed below the counter. */
  @Input() showRecent = true;

  get online() {
    return formatInt(this.data.online);
  }

  get topPages() {
    return this.data.top_pages.slice(0, this.topPagesLimit);
  }

  fmt(n: number) {
    return formatInt(n);
  }
}

// packages/dashboard-react/src/components/realtime.tsx
import type { CSSProperties } from "react";
import type { DashboardClient } from "../client.js";
import { formatInt } from "../format.js";
import { card, cardTitle, metricValue, pulseDot, row, rowLast, subtle } from "../styles.js";

export interface RealtimeProps {
  client: DashboardClient;
  /** Override the client's default site for this card. */
  siteId?: string;
  /** If set, restricts the top-pages list to the first N entries. */
  topPagesLimit?: number;
  /** Show the "recent events" feed below the counter. Default true. */
  showRecent?: boolean;
  className?: string;
  style?: CSSProperties;
}

/**
 * Live-visitor tile + quick top pages. Rendered on the server; to make
 * it tick, wrap your page in a Next.js server component that sets
 * `revalidateSeconds: 15` on createClient(), or refresh with router
 * actions / a client-side setInterval that calls router.refresh().
 */
export async function Realtime({
  client,
  siteId,
  topPagesLimit = 5,
  showRecent = true,
  className,
  style,
}: RealtimeProps) {
  const data = await client.realtime({ siteId });
  const pages = data.top_pages.slice(0, topPagesLimit);
  return (
    <div
      data-wbx-part="realtime"
      className={className}
      style={{ ...card, ...style }}
    >
      {/* Keyframes have to be in-document; ship once per instance. It's
          tiny and idempotent thanks to data-wbx-kf. */}
      <style>{PULSE_KEYFRAMES}</style>
      <div style={cardTitle}>LIVE VISITORS</div>
      <div style={{ display: "flex", alignItems: "baseline", gap: 12 }}>
        <span
          style={{
            ...pulseDot,
            animation: "wbx-pulse 1.6s ease-out infinite",
            alignSelf: "center",
          }}
          aria-hidden
        />
        <span style={metricValue}>{formatInt(data.online)}</span>
        <span style={subtle}>online now</span>
      </div>

      {pages.length > 0 && (
        <div style={{ marginTop: 20 }}>
          <div style={{ ...cardTitle, marginBottom: 8 }}>ACTIVE PAGES</div>
          {pages.map((p, i) => (
            <div
              key={p.path}
              style={i === pages.length - 1 ? rowLast : row}
            >
              <span
                style={{
                  overflow: "hidden",
                  textOverflow: "ellipsis",
                  whiteSpace: "nowrap",
                  maxWidth: "70%",
                }}
                title={p.path}
              >
                {p.path || "/"}
              </span>
              <strong style={{ fontVariantNumeric: "tabular-nums" }}>
                {formatInt(p.visitors)}
              </strong>
            </div>
          ))}
        </div>
      )}

      {showRecent && data.recent.length > 0 && (
        <div style={{ marginTop: 20 }}>
          <div style={{ ...cardTitle, marginBottom: 8 }}>RECENT</div>
          {data.recent.slice(0, 8).map((r, i, arr) => (
            <div
              key={`${r.ts}-${i}`}
              style={i === arr.length - 1 ? rowLast : row}
            >
              <span
                style={{
                  overflow: "hidden",
                  textOverflow: "ellipsis",
                  whiteSpace: "nowrap",
                  maxWidth: "70%",
                }}
              >
                {r.path || "/"}
              </span>
              <span style={subtle}>
                {r.country_code ?? ""} {r.device ?? ""}
              </span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

const PULSE_KEYFRAMES = `
@keyframes wbx-pulse {
  0%   { box-shadow: 0 0 0 0 rgba(22, 163, 74, 0.45); }
  70%  { box-shadow: 0 0 0 10px rgba(22, 163, 74, 0); }
  100% { box-shadow: 0 0 0 0 rgba(22, 163, 74, 0); }
}
`;
