// packages/dashboard-angular/src/components/top-list.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input, ViewEncapsulation } from "@angular/core";
import type { BreakdownResponse, DimensionName } from "../types";
import { countryFlag, formatInt, formatPct } from "../format";
import { WBX_CSS } from "../theme";

@Component({
  selector: "wb-top-list",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  styles: [WBX_CSS],
  template: `
    <div data-wbx data-wbx-part="top-list" [attr.data-wbx-dimension]="data.dimension">
      <div style="display: flex; justify-content: space-between; align-items: baseline;">
        <div data-wbx-title>{{ resolvedTitle }}</div>
        <div data-wbx-subtle>{{ totalFmt }}</div>
      </div>
      <div *ngIf="data.results.length === 0; else list"
           data-wbx-subtle
           style="padding: 24px 0; text-align: center;">
        No data yet.
      </div>
      <ng-template #list>
        <div style="margin-top: 8px;">
          <div *ngFor="let r of data.results" data-wbx-row>
            <div style="display: flex; align-items: center; gap: 10px; flex: 1; min-width: 0;">
              <div data-wbx-bar-track aria-hidden="true">
                <div data-wbx-bar-fill [style.width.%]="pct(r.share)"></div>
              </div>
              <span
                [title]="r.key || '(unknown)'"
                style="margin-left: -8px; padding-left: 8px; position: relative; z-index: 1;
                       overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 55%;"
              >
                <span *ngIf="data.dimension === 'country'" aria-hidden="true" style="margin-right: 6px;">
                  {{ flag(r.key) }}
                </span>
                {{ r.key || labelFallback }}
              </span>
            </div>
            <div style="display: flex; gap: 10px; align-items: baseline; font-variant-numeric: tabular-nums;">
              <strong>{{ fmt(r.value) }}</strong>
              <span data-wbx-subtle>{{ fmtPct(r.share) }}</span>
            </div>
          </div>
        </div>
      </ng-template>
    </div>
  `,
})
export class TopListComponent {
  /** Response from `client.breakdown(window, dimension)`. */
  @Input({ required: true }) data!: BreakdownResponse;

  /** Override the card title; defaults to a nice label per dimension. */
  @Input() title?: string;

  readonly labelFallback = "(direct / unknown)";

  get resolvedTitle(): string {
    return (this.title ?? this.defaultTitle(this.data.dimension)).toUpperCase();
  }

  get totalFmt() {
    return formatInt(this.data.total);
  }

  pct(share: number) {
    return Math.max(2, Math.min(100, share * 100));
  }

  fmt(n: number) {
    return formatInt(n);
  }
  fmtPct(n: number) {
    return formatPct(n);
  }
  flag(cc: string) {
    return countryFlag(cc);
  }

  private defaultTitle(d: DimensionName): string {
    switch (d) {
      case "path":
        return "Top pages";
      case "hostname":
        return "Top hostnames";
      case "referrer_host":
        return "Top referrers";
      case "country":
        return "Top countries";
      case "device":
        return "Devices";
      case "browser":
        return "Browsers";
      case "os":
        return "Operating systems";
      case "utm_source":
        return "UTM sources";
      case "utm_medium":
        return "UTM mediums";
      case "utm_campaign":
        return "UTM campaigns";
      case "event_name":
        return "Top events";
    }
  }
}

// packages/dashboard-react/src/components/top-list.tsx
import type { CSSProperties } from "react";
import type { DashboardClient } from "../client.js";
import type {
  DimensionName,
  Filters,
  MetricName,
  WindowSpec,
} from "../types.js";
import { countryFlag, formatInt, formatPct } from "../format.js";
import { barFill, barTrack, card, cardTitle, row, rowLast, subtle } from "../styles.js";

export interface TopListProps {
  client: DashboardClient;
  dimension: DimensionName;
  window?: WindowSpec;
  metric?: MetricName;
  siteId?: string;
  filters?: Filters;
  limit?: number;
  /** Override the header title. Defaults to a nice label per dimension. */
  title?: string;
  /** Optional cell formatter for the dimension key (e.g. humanize hosts). */
  renderKey?: (k: string, dimension: DimensionName) => React.ReactNode;
  className?: string;
  style?: CSSProperties;
}

/**
 * Horizontal-bar list view used for every breakdown dimension: top
 * pages, referrers, countries, devices, browsers, OSes, UTM params, etc.
 * Each row is a compact bar overlaid with label + count + share.
 */
export async function TopList({
  client,
  dimension,
  window = "7d",
  metric = "visitors",
  siteId,
  filters,
  limit = 10,
  title,
  renderKey,
  className,
  style,
}: TopListProps) {
  const data = await client.breakdown(window, dimension, {
    siteId,
    metric,
    filters,
    limit,
  });
  const display = title ?? defaultTitle(dimension);
  const results = data.results;
  const render = renderKey ?? defaultRenderKey;
  const maxShare = Math.max(...results.map((r) => r.share)) || 1;

  return (
    <div
      data-wbx-part="top-list"
      data-wbx-dimension={dimension}
      className={className}
      style={{ ...card, ...style }}
    >
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "baseline",
        }}
      >
        <div style={cardTitle}>{display.toUpperCase()}</div>
        <div style={subtle}>{formatInt(data.total)}</div>
      </div>
      {results.length === 0 ? (
        <div style={{ ...subtle, padding: "24px 0", textAlign: "center" }}>
          No data yet.
        </div>
      ) : (
        <div style={{ marginTop: 8 }}>
          {results.map((r, i) => (
            <div
              key={`${r.key}-${i}`}
              style={i === results.length - 1 ? rowLast : row}
            >
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 10,
                  flex: 1,
                  minWidth: 0,
                }}
              >
                <div style={barTrack} aria-hidden>
                  <div style={barFill(r.share / maxShare)} />
                </div>
                <span
                  style={{
                    position: "absolute",
                    // visually-hidden twin for screen readers
                    width: 1,
                    height: 1,
                    overflow: "hidden",
                    clipPath: "inset(50%)",
                  }}
                >
                  {Math.round(r.share * 100)}%
                </span>
                <span
                  style={{
                    marginLeft: -8,
                    paddingLeft: 8,
                    position: "relative",
                    zIndex: 1,
                    overflow: "hidden",
                    textOverflow: "ellipsis",
                    whiteSpace: "nowrap",
                    maxWidth: "55%",
                  }}
                  title={r.key || "(unknown)"}
                >
                  {render(r.key, dimension)}
                </span>
              </div>
              <div
                style={{
                  fontVariantNumeric: "tabular-nums",
                  display: "flex",
                  gap: 10,
                  alignItems: "baseline",
                }}
              >
                <strong>{formatInt(r.value)}</strong>
                <span style={subtle}>{formatPct(r.share)}</span>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function defaultTitle(d: DimensionName): string {
  switch (d) {
    case "path":
      return "Top pages";
    case "hostname":
      return "Top hostnames";
    case "referrer_host":
      return "Top referrers";
    case "country":
      return "Top countries";
    case "device":
      return "Devices";
    case "browser":
      return "Browsers";
    case "os":
      return "Operating systems";
    case "utm_source":
      return "UTM sources";
    case "utm_medium":
      return "UTM mediums";
    case "utm_campaign":
      return "UTM campaigns";
    case "event_name":
      return "Top events";
  }
}

function defaultRenderKey(k: string, d: DimensionName): React.ReactNode {
  const label = k && k !== "" ? k : "(direct / unknown)";
  if (d === "country") {
    return (
      <span>
        <span aria-hidden style={{ marginRight: 6 }}>
          {countryFlag(k)}
        </span>
        {label}
      </span>
    );
  }
  return label;
}
